services:
  - type: web
    name: cbt-test
    env: node
    rootDirectory: backend
    buildCommand: cd ../frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Database configuration
      - key: DB_USER
        fromDatabase:
          name: cbt-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: cbt-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: cbt-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: cbt-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: cbt-db
          property: database
      # JWT Secret for authentication
      - key: JWT_SECRET
        generateValue: true
      # Frontend URL for CORS
      - key: FRONTEND_URL
        value: https://cbt-test.onrender.com
      # Telegram Bot Token (optional - set this if you're using Telegram features)
      - key: TELEGRAM_BOT_TOKEN
        value: ""
    plan: free
    region: oregon
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: cbt-db
    databaseName: cbt
    user: cbt_user
    plan: free
    region: oregon
