services:
  - type: web
    name: cbt-test
    env: node
    rootDirectory: backend
    buildCommand: cd ../frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Add other environment variables from your .env file here
      - key: DATABASE_URL
        fromDatabase:
          name: cbt-db
          property: connectionString
    plan: free
    region: oregon
    healthCheckPath: /api/health
    autoDeploy: true

# Uncomment and configure if you need a database
# databases:
#   - name: cbt-db
#     databaseName: cbt
#     user: cbt_user
#     plan: free
#     region: oregon
